// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynveufqrkfwwhmxyoaks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InludmV1ZnFya2Z3d2hteHlvYWtzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MzA1NTYsImV4cCI6MjA2NzUwNjU1Nn0.lRQKxQl82fxmdiBOD1iQ5xeewJ4ndTLovJhHVwCn2Uk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});